// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: test.proto
// Protobuf Java Version: 4.30.2

package com.github.peterrk.protocache.pb;

/**
 * Protobuf type {@code test.ArrMap}
 */
public final class ArrMap extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:test.ArrMap)
    ArrMapOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 30,
      /* patch= */ 2,
      /* suffix= */ "",
      ArrMap.class.getName());
  }
  // Use ArrMap.newBuilder() to construct.
  private ArrMap(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private ArrMap() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.github.peterrk.protocache.pb.Test.internal_static_test_ArrMap_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @java.lang.Override
  protected com.google.protobuf.MapFieldReflectionAccessor internalGetMapFieldReflection(
      int number) {
    switch (number) {
      case 1:
        return internalGet();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.github.peterrk.protocache.pb.Test.internal_static_test_ArrMap_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.github.peterrk.protocache.pb.ArrMap.class, com.github.peterrk.protocache.pb.ArrMap.Builder.class);
  }

  public interface ArrayOrBuilder extends
      // @@protoc_insertion_point(interface_extends:test.ArrMap.Array)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated float _ = 1;</code>
     * @return A list containing the .
     */
    java.util.List<java.lang.Float> getList();
    /**
     * <code>repeated float _ = 1;</code>
     * @return The count of .
     */
    int getCount();
    /**
     * <code>repeated float _ = 1;</code>
     * @param index The index of the element to return.
     * @return The  at the given index.
     */
    float get(int index);
  }
  /**
   * Protobuf type {@code test.ArrMap.Array}
   */
  public static final class Array extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:test.ArrMap.Array)
      ArrayOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 30,
        /* patch= */ 2,
        /* suffix= */ "",
        Array.class.getName());
    }
    // Use Array.newBuilder() to construct.
    private Array(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private Array() {
      _ = emptyFloatList();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.peterrk.protocache.pb.Test.internal_static_test_ArrMap_Array_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.peterrk.protocache.pb.Test.internal_static_test_ArrMap_Array_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.peterrk.protocache.pb.ArrMap.Array.class, com.github.peterrk.protocache.pb.ArrMap.Array.Builder.class);
    }

    public static final int __FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private com.google.protobuf.Internal.FloatList _ =
        emptyFloatList();
    /**
     * <code>repeated float _ = 1;</code>
     * @return A list containing the .
     */
    @java.lang.Override
    public java.util.List<java.lang.Float>
        getList() {
      return _;
    }
    /**
     * <code>repeated float _ = 1;</code>
     * @return The count of .
     */
    public int getCount() {
      return _.size();
    }
    /**
     * <code>repeated float _ = 1;</code>
     * @param index The index of the element to return.
     * @return The  at the given index.
     */
    public float get(int index) {
      return _.getFloat(index);
    }
    private int MemoizedSerializedSize = -1;

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (getList().size() > 0) {
        output.writeUInt32NoTag(10);
        output.writeUInt32NoTag(MemoizedSerializedSize);
      }
      for (int i = 0; i < _.size(); i++) {
        output.writeFloatNoTag(_.getFloat(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        dataSize = 4 * getList().size();
        size += dataSize;
        if (!getList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        MemoizedSerializedSize = dataSize;
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.github.peterrk.protocache.pb.ArrMap.Array)) {
        return super.equals(obj);
      }
      com.github.peterrk.protocache.pb.ArrMap.Array other = (com.github.peterrk.protocache.pb.ArrMap.Array) obj;

      if (!getList()
          .equals(other.getList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getCount() > 0) {
        hash = (37 * hash) + __FIELD_NUMBER;
        hash = (53 * hash) + getList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.github.peterrk.protocache.pb.ArrMap.Array parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.peterrk.protocache.pb.ArrMap.Array parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.peterrk.protocache.pb.ArrMap.Array parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.peterrk.protocache.pb.ArrMap.Array parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.peterrk.protocache.pb.ArrMap.Array parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.peterrk.protocache.pb.ArrMap.Array parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.peterrk.protocache.pb.ArrMap.Array parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.github.peterrk.protocache.pb.ArrMap.Array parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.github.peterrk.protocache.pb.ArrMap.Array parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.github.peterrk.protocache.pb.ArrMap.Array parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.github.peterrk.protocache.pb.ArrMap.Array parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.github.peterrk.protocache.pb.ArrMap.Array parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.github.peterrk.protocache.pb.ArrMap.Array prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code test.ArrMap.Array}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:test.ArrMap.Array)
        com.github.peterrk.protocache.pb.ArrMap.ArrayOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.github.peterrk.protocache.pb.Test.internal_static_test_ArrMap_Array_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.github.peterrk.protocache.pb.Test.internal_static_test_ArrMap_Array_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.github.peterrk.protocache.pb.ArrMap.Array.class, com.github.peterrk.protocache.pb.ArrMap.Array.Builder.class);
      }

      // Construct using com.github.peterrk.protocache.pb.ArrMap.Array.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        _ = emptyFloatList();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.github.peterrk.protocache.pb.Test.internal_static_test_ArrMap_Array_descriptor;
      }

      @java.lang.Override
      public com.github.peterrk.protocache.pb.ArrMap.Array getDefaultInstanceForType() {
        return com.github.peterrk.protocache.pb.ArrMap.Array.getDefaultInstance();
      }

      @java.lang.Override
      public com.github.peterrk.protocache.pb.ArrMap.Array build() {
        com.github.peterrk.protocache.pb.ArrMap.Array result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.github.peterrk.protocache.pb.ArrMap.Array buildPartial() {
        com.github.peterrk.protocache.pb.ArrMap.Array result = new com.github.peterrk.protocache.pb.ArrMap.Array(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.github.peterrk.protocache.pb.ArrMap.Array result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          _.makeImmutable();
          result._ = _;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.github.peterrk.protocache.pb.ArrMap.Array) {
          return mergeFrom((com.github.peterrk.protocache.pb.ArrMap.Array)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.github.peterrk.protocache.pb.ArrMap.Array other) {
        if (other == com.github.peterrk.protocache.pb.ArrMap.Array.getDefaultInstance()) return this;
        if (!other._.isEmpty()) {
          if (_.isEmpty()) {
            _ = other._;
            _.makeImmutable();
            bitField0_ |= 0x00000001;
          } else {
            ensureIsMutable();
            _.addAll(other._);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 13: {
                float v = input.readFloat();
                ensureIsMutable();
                _.addFloat(v);
                break;
              } // case 13
              case 10: {
                int length = input.readRawVarint32();
                int limit = input.pushLimit(length);
                int alloc = length > 4096 ? 4096 : length;
                ensureIsMutable(alloc / 4);
                while (input.getBytesUntilLimit() > 0) {
                  _.addFloat(input.readFloat());
                }
                input.popLimit(limit);
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.Internal.FloatList _ = emptyFloatList();
      private void ensureIsMutable() {
        if (!_.isModifiable()) {
          _ = makeMutableCopy(_);
        }
        bitField0_ |= 0x00000001;
      }
      private void ensureIsMutable(int capacity) {
        if (!_.isModifiable()) {
          _ = makeMutableCopy(_, capacity);
        }
        bitField0_ |= 0x00000001;
      }
      /**
       * <code>repeated float _ = 1;</code>
       * @return A list containing the .
       */
      public java.util.List<java.lang.Float>
          getList() {
        _.makeImmutable();
        return _;
      }
      /**
       * <code>repeated float _ = 1;</code>
       * @return The count of .
       */
      public int getCount() {
        return _.size();
      }
      /**
       * <code>repeated float _ = 1;</code>
       * @param index The index of the element to return.
       * @return The  at the given index.
       */
      public float get(int index) {
        return _.getFloat(index);
      }
      /**
       * <code>repeated float _ = 1;</code>
       * @param index The index to set the value at.
       * @param value The  to set.
       * @return This builder for chaining.
       */
      public Builder set(
          int index, float value) {

        ensureIsMutable();
        _.setFloat(index, value);
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>repeated float _ = 1;</code>
       * @param value The  to add.
       * @return This builder for chaining.
       */
      public Builder add(float value) {

        ensureIsMutable();
        _.addFloat(value);
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>repeated float _ = 1;</code>
       * @param values The  to add.
       * @return This builder for chaining.
       */
      public Builder addAll(
          java.lang.Iterable<? extends java.lang.Float> values) {
        ensureIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, _);
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:test.ArrMap.Array)
    }

    // @@protoc_insertion_point(class_scope:test.ArrMap.Array)
    private static final com.github.peterrk.protocache.pb.ArrMap.Array DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.github.peterrk.protocache.pb.ArrMap.Array();
    }

    public static com.github.peterrk.protocache.pb.ArrMap.Array getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Array>
        PARSER = new com.google.protobuf.AbstractParser<Array>() {
      @java.lang.Override
      public Array parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Array> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Array> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.github.peterrk.protocache.pb.ArrMap.Array getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public static final int __FIELD_NUMBER = 1;
  private static final class DefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, com.github.peterrk.protocache.pb.ArrMap.Array> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, com.github.peterrk.protocache.pb.ArrMap.Array>newDefaultInstance(
                com.github.peterrk.protocache.pb.Test.internal_static_test_ArrMap_Entry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.MESSAGE,
                com.github.peterrk.protocache.pb.ArrMap.Array.getDefaultInstance());
  }
  @SuppressWarnings("serial")
  private com.google.protobuf.MapField<
      java.lang.String, com.github.peterrk.protocache.pb.ArrMap.Array> _;
  private com.google.protobuf.MapField<java.lang.String, com.github.peterrk.protocache.pb.ArrMap.Array>
  internalGet() {
    if (_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          DefaultEntryHolder.defaultEntry);
    }
    return _;
  }
  public int getCount() {
    return internalGet().getMap().size();
  }
  /**
   * <code>map&lt;string, .test.ArrMap.Array&gt; _ = 1;</code>
   */
  @java.lang.Override
  public boolean contains(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    return internalGet().getMap().containsKey(key);
  }
  /**
   * Use {@link #getMap()} instead.
   */
  @java.lang.Override
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, com.github.peterrk.protocache.pb.ArrMap.Array> get() {
    return getMap();
  }
  /**
   * <code>map&lt;string, .test.ArrMap.Array&gt; _ = 1;</code>
   */
  @java.lang.Override
  public java.util.Map<java.lang.String, com.github.peterrk.protocache.pb.ArrMap.Array> getMap() {
    return internalGet().getMap();
  }
  /**
   * <code>map&lt;string, .test.ArrMap.Array&gt; _ = 1;</code>
   */
  @java.lang.Override
  public /* nullable */
com.github.peterrk.protocache.pb.ArrMap.Array getOrDefault(
      java.lang.String key,
      /* nullable */
com.github.peterrk.protocache.pb.ArrMap.Array defaultValue) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, com.github.peterrk.protocache.pb.ArrMap.Array> map =
        internalGet().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;string, .test.ArrMap.Array&gt; _ = 1;</code>
   */
  @java.lang.Override
  public com.github.peterrk.protocache.pb.ArrMap.Array getOrThrow(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, com.github.peterrk.protocache.pb.ArrMap.Array> map =
        internalGet().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    com.google.protobuf.GeneratedMessage
      .serializeStringMapTo(
        output,
        internalGet(),
        DefaultEntryHolder.defaultEntry,
        1);
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (java.util.Map.Entry<java.lang.String, com.github.peterrk.protocache.pb.ArrMap.Array> entry
         : internalGet().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, com.github.peterrk.protocache.pb.ArrMap.Array>
      __ = DefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, __);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.github.peterrk.protocache.pb.ArrMap)) {
      return super.equals(obj);
    }
    com.github.peterrk.protocache.pb.ArrMap other = (com.github.peterrk.protocache.pb.ArrMap) obj;

    if (!internalGet().equals(
        other.internalGet())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (!internalGet().getMap().isEmpty()) {
      hash = (37 * hash) + __FIELD_NUMBER;
      hash = (53 * hash) + internalGet().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.github.peterrk.protocache.pb.ArrMap parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.peterrk.protocache.pb.ArrMap parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.peterrk.protocache.pb.ArrMap parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.peterrk.protocache.pb.ArrMap parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.peterrk.protocache.pb.ArrMap parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.peterrk.protocache.pb.ArrMap parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.peterrk.protocache.pb.ArrMap parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.github.peterrk.protocache.pb.ArrMap parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.github.peterrk.protocache.pb.ArrMap parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.github.peterrk.protocache.pb.ArrMap parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.github.peterrk.protocache.pb.ArrMap parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.github.peterrk.protocache.pb.ArrMap parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.github.peterrk.protocache.pb.ArrMap prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code test.ArrMap}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:test.ArrMap)
      com.github.peterrk.protocache.pb.ArrMapOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.peterrk.protocache.pb.Test.internal_static_test_ArrMap_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapFieldReflectionAccessor internalGetMapFieldReflection(
        int number) {
      switch (number) {
        case 1:
          return internalGet();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapFieldReflectionAccessor internalGetMutableMapFieldReflection(
        int number) {
      switch (number) {
        case 1:
          return internalGetMutable();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.peterrk.protocache.pb.Test.internal_static_test_ArrMap_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.peterrk.protocache.pb.ArrMap.class, com.github.peterrk.protocache.pb.ArrMap.Builder.class);
    }

    // Construct using com.github.peterrk.protocache.pb.ArrMap.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      internalGetMutable().clear();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.github.peterrk.protocache.pb.Test.internal_static_test_ArrMap_descriptor;
    }

    @java.lang.Override
    public com.github.peterrk.protocache.pb.ArrMap getDefaultInstanceForType() {
      return com.github.peterrk.protocache.pb.ArrMap.getDefaultInstance();
    }

    @java.lang.Override
    public com.github.peterrk.protocache.pb.ArrMap build() {
      com.github.peterrk.protocache.pb.ArrMap result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.github.peterrk.protocache.pb.ArrMap buildPartial() {
      com.github.peterrk.protocache.pb.ArrMap result = new com.github.peterrk.protocache.pb.ArrMap(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.github.peterrk.protocache.pb.ArrMap result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result._ = internalGet().build(DefaultEntryHolder.defaultEntry);
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.github.peterrk.protocache.pb.ArrMap) {
        return mergeFrom((com.github.peterrk.protocache.pb.ArrMap)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.github.peterrk.protocache.pb.ArrMap other) {
      if (other == com.github.peterrk.protocache.pb.ArrMap.getDefaultInstance()) return this;
      internalGetMutable().mergeFrom(
          other.internalGet());
      bitField0_ |= 0x00000001;
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.MapEntry<java.lang.String, com.github.peterrk.protocache.pb.ArrMap.Array>
              __ = input.readMessage(
                  DefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              internalGetMutable().ensureBuilderMap().put(
                  __.getKey(), __.getValue());
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private static final class Converter implements com.google.protobuf.MapFieldBuilder.Converter<java.lang.String, com.github.peterrk.protocache.pb.ArrMap.ArrayOrBuilder, com.github.peterrk.protocache.pb.ArrMap.Array> {
      @java.lang.Override
      public com.github.peterrk.protocache.pb.ArrMap.Array build(com.github.peterrk.protocache.pb.ArrMap.ArrayOrBuilder val) {
        if (val instanceof com.github.peterrk.protocache.pb.ArrMap.Array) { return (com.github.peterrk.protocache.pb.ArrMap.Array) val; }
        return ((com.github.peterrk.protocache.pb.ArrMap.Array.Builder) val).build();
      }

      @java.lang.Override
      public com.google.protobuf.MapEntry<java.lang.String, com.github.peterrk.protocache.pb.ArrMap.Array> defaultEntry() {
        return DefaultEntryHolder.defaultEntry;
      }
    };
    private static final Converter Converter = new Converter();

    private com.google.protobuf.MapFieldBuilder<
        java.lang.String, com.github.peterrk.protocache.pb.ArrMap.ArrayOrBuilder, com.github.peterrk.protocache.pb.ArrMap.Array, com.github.peterrk.protocache.pb.ArrMap.Array.Builder> _;
    private com.google.protobuf.MapFieldBuilder<java.lang.String, com.github.peterrk.protocache.pb.ArrMap.ArrayOrBuilder, com.github.peterrk.protocache.pb.ArrMap.Array, com.github.peterrk.protocache.pb.ArrMap.Array.Builder>
        internalGet() {
      if (_ == null) {
        return new com.google.protobuf.MapFieldBuilder<>(Converter);
      }
      return _;
    }
    private com.google.protobuf.MapFieldBuilder<java.lang.String, com.github.peterrk.protocache.pb.ArrMap.ArrayOrBuilder, com.github.peterrk.protocache.pb.ArrMap.Array, com.github.peterrk.protocache.pb.ArrMap.Array.Builder>
        internalGetMutable() {
      if (_ == null) {
        _ = new com.google.protobuf.MapFieldBuilder<>(Converter);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return _;
    }
    public int getCount() {
      return internalGet().ensureBuilderMap().size();
    }
    /**
     * <code>map&lt;string, .test.ArrMap.Array&gt; _ = 1;</code>
     */
    @java.lang.Override
    public boolean contains(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      return internalGet().ensureBuilderMap().containsKey(key);
    }
    /**
     * Use {@link #getMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, com.github.peterrk.protocache.pb.ArrMap.Array> get() {
      return getMap();
    }
    /**
     * <code>map&lt;string, .test.ArrMap.Array&gt; _ = 1;</code>
     */
    @java.lang.Override
    public java.util.Map<java.lang.String, com.github.peterrk.protocache.pb.ArrMap.Array> getMap() {
      return internalGet().getImmutableMap();
    }
    /**
     * <code>map&lt;string, .test.ArrMap.Array&gt; _ = 1;</code>
     */
    @java.lang.Override
    public /* nullable */
com.github.peterrk.protocache.pb.ArrMap.Array getOrDefault(
        java.lang.String key,
        /* nullable */
com.github.peterrk.protocache.pb.ArrMap.Array defaultValue) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, com.github.peterrk.protocache.pb.ArrMap.ArrayOrBuilder> map = internalGetMutable().ensureBuilderMap();
      return map.containsKey(key) ? Converter.build(map.get(key)) : defaultValue;
    }
    /**
     * <code>map&lt;string, .test.ArrMap.Array&gt; _ = 1;</code>
     */
    @java.lang.Override
    public com.github.peterrk.protocache.pb.ArrMap.Array getOrThrow(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, com.github.peterrk.protocache.pb.ArrMap.ArrayOrBuilder> map = internalGetMutable().ensureBuilderMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return Converter.build(map.get(key));
    }
    /**
     * <code>map&lt;string, .test.ArrMap.Array&gt; _ = 1;</code>
     */
    public Builder remove(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      internalGetMutable().ensureBuilderMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, com.github.peterrk.protocache.pb.ArrMap.Array>
        getMutable() {
      bitField0_ |= 0x00000001;
      return internalGetMutable().ensureMessageMap();
    }
    /**
     * <code>map&lt;string, .test.ArrMap.Array&gt; _ = 1;</code>
     */
    public Builder put(
        java.lang.String key,
        com.github.peterrk.protocache.pb.ArrMap.Array value) {
      if (key == null) { throw new NullPointerException("map key"); }
      if (value == null) { throw new NullPointerException("map value"); }
      internalGetMutable().ensureBuilderMap()
          .put(key, value);
      bitField0_ |= 0x00000001;
      return this;
    }
    /**
     * <code>map&lt;string, .test.ArrMap.Array&gt; _ = 1;</code>
     */
    public Builder putAll(
        java.util.Map<java.lang.String, com.github.peterrk.protocache.pb.ArrMap.Array> values) {
      for (java.util.Map.Entry<java.lang.String, com.github.peterrk.protocache.pb.ArrMap.Array> e : values.entrySet()) {
        if (e.getKey() == null || e.getValue() == null) {
          throw new NullPointerException();
        }
      }
      internalGetMutable().ensureBuilderMap()
          .putAll(values);
      bitField0_ |= 0x00000001;
      return this;
    }
    /**
     * <code>map&lt;string, .test.ArrMap.Array&gt; _ = 1;</code>
     */
    public com.github.peterrk.protocache.pb.ArrMap.Array.Builder putBuilderIfAbsent(
        java.lang.String key) {
      java.util.Map<java.lang.String, com.github.peterrk.protocache.pb.ArrMap.ArrayOrBuilder> builderMap = internalGetMutable().ensureBuilderMap();
      com.github.peterrk.protocache.pb.ArrMap.ArrayOrBuilder entry = builderMap.get(key);
      if (entry == null) {
        entry = com.github.peterrk.protocache.pb.ArrMap.Array.newBuilder();
        builderMap.put(key, entry);
      }
      if (entry instanceof com.github.peterrk.protocache.pb.ArrMap.Array) {
        entry = ((com.github.peterrk.protocache.pb.ArrMap.Array) entry).toBuilder();
        builderMap.put(key, entry);
      }
      return (com.github.peterrk.protocache.pb.ArrMap.Array.Builder) entry;
    }

    // @@protoc_insertion_point(builder_scope:test.ArrMap)
  }

  // @@protoc_insertion_point(class_scope:test.ArrMap)
  private static final com.github.peterrk.protocache.pb.ArrMap DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.github.peterrk.protocache.pb.ArrMap();
  }

  public static com.github.peterrk.protocache.pb.ArrMap getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ArrMap>
      PARSER = new com.google.protobuf.AbstractParser<ArrMap>() {
    @java.lang.Override
    public ArrMap parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ArrMap> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ArrMap> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.github.peterrk.protocache.pb.ArrMap getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

