// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test.proto

package com.github.peterrk.protocache.pb;

/**
 * Protobuf type {@code test.ArrMap}
 */
public final class ArrMap extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:test.ArrMap)
    ArrMapOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ArrMap.newBuilder() to construct.
  private ArrMap(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ArrMap() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ArrMap();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ArrMap(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              _ = com.google.protobuf.MapField.newMapField(
                  DefaultEntryHolder.defaultEntry);
              mutable_bitField0_ |= 0x00000001;
            }
            com.google.protobuf.MapEntry<java.lang.String, com.github.peterrk.protocache.pb.ArrMap.Array>
            __ = input.readMessage(
                DefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
            _.getMutableMap().put(
                __.getKey(), __.getValue());
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.github.peterrk.protocache.pb.Test.internal_static_test_ArrMap_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @java.lang.Override
  protected com.google.protobuf.MapField internalGetMapField(
      int number) {
    switch (number) {
      case 1:
        return internalGet();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.github.peterrk.protocache.pb.Test.internal_static_test_ArrMap_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.github.peterrk.protocache.pb.ArrMap.class, com.github.peterrk.protocache.pb.ArrMap.Builder.class);
  }

  public interface ArrayOrBuilder extends
      // @@protoc_insertion_point(interface_extends:test.ArrMap.Array)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated float _ = 1;</code>
     * @return A list containing the .
     */
    java.util.List<java.lang.Float> getList();
    /**
     * <code>repeated float _ = 1;</code>
     * @return The count of .
     */
    int getCount();
    /**
     * <code>repeated float _ = 1;</code>
     * @param index The index of the element to return.
     * @return The  at the given index.
     */
    float get(int index);
  }
  /**
   * Protobuf type {@code test.ArrMap.Array}
   */
  public static final class Array extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:test.ArrMap.Array)
      ArrayOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Array.newBuilder() to construct.
    private Array(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Array() {
      _ = emptyFloatList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Array();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Array(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 13: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                _ = newFloatList();
                mutable_bitField0_ |= 0x00000001;
              }
              _.addFloat(input.readFloat());
              break;
            }
            case 10: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000001) != 0) && input.getBytesUntilLimit() > 0) {
                _ = newFloatList();
                mutable_bitField0_ |= 0x00000001;
              }
              while (input.getBytesUntilLimit() > 0) {
                _.addFloat(input.readFloat());
              }
              input.popLimit(limit);
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          _.makeImmutable(); // C
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.peterrk.protocache.pb.Test.internal_static_test_ArrMap_Array_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.peterrk.protocache.pb.Test.internal_static_test_ArrMap_Array_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.peterrk.protocache.pb.ArrMap.Array.class, com.github.peterrk.protocache.pb.ArrMap.Array.Builder.class);
    }

    public static final int __FIELD_NUMBER = 1;
    private com.google.protobuf.Internal.FloatList _;
    /**
     * <code>repeated float _ = 1;</code>
     * @return A list containing the .
     */
    @java.lang.Override
    public java.util.List<java.lang.Float>
        getList() {
      return _;
    }
    /**
     * <code>repeated float _ = 1;</code>
     * @return The count of .
     */
    public int getCount() {
      return _.size();
    }
    /**
     * <code>repeated float _ = 1;</code>
     * @param index The index of the element to return.
     * @return The  at the given index.
     */
    public float get(int index) {
      return _.getFloat(index);
    }
    private int MemoizedSerializedSize = -1;

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (getList().size() > 0) {
        output.writeUInt32NoTag(10);
        output.writeUInt32NoTag(MemoizedSerializedSize);
      }
      for (int i = 0; i < _.size(); i++) {
        output.writeFloatNoTag(_.getFloat(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        dataSize = 4 * getList().size();
        size += dataSize;
        if (!getList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        MemoizedSerializedSize = dataSize;
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.github.peterrk.protocache.pb.ArrMap.Array)) {
        return super.equals(obj);
      }
      com.github.peterrk.protocache.pb.ArrMap.Array other = (com.github.peterrk.protocache.pb.ArrMap.Array) obj;

      if (!getList()
          .equals(other.getList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getCount() > 0) {
        hash = (37 * hash) + __FIELD_NUMBER;
        hash = (53 * hash) + getList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.github.peterrk.protocache.pb.ArrMap.Array parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.peterrk.protocache.pb.ArrMap.Array parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.peterrk.protocache.pb.ArrMap.Array parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.peterrk.protocache.pb.ArrMap.Array parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.peterrk.protocache.pb.ArrMap.Array parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.peterrk.protocache.pb.ArrMap.Array parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.peterrk.protocache.pb.ArrMap.Array parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.github.peterrk.protocache.pb.ArrMap.Array parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.github.peterrk.protocache.pb.ArrMap.Array parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.github.peterrk.protocache.pb.ArrMap.Array parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.github.peterrk.protocache.pb.ArrMap.Array parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.github.peterrk.protocache.pb.ArrMap.Array parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.github.peterrk.protocache.pb.ArrMap.Array prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code test.ArrMap.Array}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:test.ArrMap.Array)
        com.github.peterrk.protocache.pb.ArrMap.ArrayOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.github.peterrk.protocache.pb.Test.internal_static_test_ArrMap_Array_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.github.peterrk.protocache.pb.Test.internal_static_test_ArrMap_Array_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.github.peterrk.protocache.pb.ArrMap.Array.class, com.github.peterrk.protocache.pb.ArrMap.Array.Builder.class);
      }

      // Construct using com.github.peterrk.protocache.pb.ArrMap.Array.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
//      @java.lang.Override
//      public Builder clear() {
//        super.clear();
//        _ = emptyFloatList();
//        bitField0_ = (bitField0_ & ~0x00000001);
//        return this;
//      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.github.peterrk.protocache.pb.Test.internal_static_test_ArrMap_Array_descriptor;
      }

      @java.lang.Override
      public com.github.peterrk.protocache.pb.ArrMap.Array getDefaultInstanceForType() {
        return com.github.peterrk.protocache.pb.ArrMap.Array.getDefaultInstance();
      }

      @java.lang.Override
      public com.github.peterrk.protocache.pb.ArrMap.Array build() {
        com.github.peterrk.protocache.pb.ArrMap.Array result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.github.peterrk.protocache.pb.ArrMap.Array buildPartial() {
        com.github.peterrk.protocache.pb.ArrMap.Array result = new com.github.peterrk.protocache.pb.ArrMap.Array(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) != 0)) {
          _.makeImmutable();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result._ = _;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.github.peterrk.protocache.pb.ArrMap.Array) {
          return mergeFrom((com.github.peterrk.protocache.pb.ArrMap.Array)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.github.peterrk.protocache.pb.ArrMap.Array other) {
        if (other == com.github.peterrk.protocache.pb.ArrMap.Array.getDefaultInstance()) return this;
        if (!other._.isEmpty()) {
          if (_.isEmpty()) {
            _ = other._;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureIsMutable();
            _.addAll(other._);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.github.peterrk.protocache.pb.ArrMap.Array parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.github.peterrk.protocache.pb.ArrMap.Array) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.Internal.FloatList _ = emptyFloatList();
      private void ensureIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          _ = mutableCopy(_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated float _ = 1;</code>
       * @return A list containing the .
       */
      public java.util.List<java.lang.Float>
          getList() {
        return ((bitField0_ & 0x00000001) != 0) ?
                 java.util.Collections.unmodifiableList(_) : _;
      }
      /**
       * <code>repeated float _ = 1;</code>
       * @return The count of .
       */
      public int getCount() {
        return _.size();
      }
      /**
       * <code>repeated float _ = 1;</code>
       * @param index The index of the element to return.
       * @return The  at the given index.
       */
      public float get(int index) {
        return _.getFloat(index);
      }
      /**
       * <code>repeated float _ = 1;</code>
       * @param index The index to set the value at.
       * @param value The  to set.
       * @return This builder for chaining.
       */
      public Builder set(
          int index, float value) {
        ensureIsMutable();
        _.setFloat(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated float _ = 1;</code>
       * @param value The  to add.
       * @return This builder for chaining.
       */
      public Builder add(float value) {
        ensureIsMutable();
        _.addFloat(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated float _ = 1;</code>
       * @param values The  to add.
       * @return This builder for chaining.
       */
      public Builder addAll(
          java.lang.Iterable<? extends java.lang.Float> values) {
        ensureIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, _);
        onChanged();
        return this;
      }
      /**
       * <code>repeated float _ = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clear() {
        _ = emptyFloatList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:test.ArrMap.Array)
    }

    // @@protoc_insertion_point(class_scope:test.ArrMap.Array)
    private static final com.github.peterrk.protocache.pb.ArrMap.Array DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.github.peterrk.protocache.pb.ArrMap.Array();
    }

    public static com.github.peterrk.protocache.pb.ArrMap.Array getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Array>
        PARSER = new com.google.protobuf.AbstractParser<Array>() {
      @java.lang.Override
      public Array parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Array(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Array> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Array> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.github.peterrk.protocache.pb.ArrMap.Array getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public static final int __FIELD_NUMBER = 1;
  private static final class DefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, com.github.peterrk.protocache.pb.ArrMap.Array> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, com.github.peterrk.protocache.pb.ArrMap.Array>newDefaultInstance(
                com.github.peterrk.protocache.pb.Test.internal_static_test_ArrMap_Entry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.MESSAGE,
                com.github.peterrk.protocache.pb.ArrMap.Array.getDefaultInstance());
  }
  private com.google.protobuf.MapField<
      java.lang.String, com.github.peterrk.protocache.pb.ArrMap.Array> _;
  private com.google.protobuf.MapField<java.lang.String, com.github.peterrk.protocache.pb.ArrMap.Array>
  internalGet() {
    if (_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          DefaultEntryHolder.defaultEntry);
    }
    return _;
  }

  public int getCount() {
    return internalGet().getMap().size();
  }
  /**
   * <code>map&lt;string, .test.ArrMap.Array&gt; _ = 1;</code>
   */

  @java.lang.Override
  public boolean contains(
      java.lang.String key) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    return internalGet().getMap().containsKey(key);
  }
  /**
   * Use {@link #getMap()} instead.
   */
  @java.lang.Override
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, com.github.peterrk.protocache.pb.ArrMap.Array> get() {
    return getMap();
  }
  /**
   * <code>map&lt;string, .test.ArrMap.Array&gt; _ = 1;</code>
   */
  @java.lang.Override

  public java.util.Map<java.lang.String, com.github.peterrk.protocache.pb.ArrMap.Array> getMap() {
    return internalGet().getMap();
  }
  /**
   * <code>map&lt;string, .test.ArrMap.Array&gt; _ = 1;</code>
   */
  @java.lang.Override

  public com.github.peterrk.protocache.pb.ArrMap.Array getOrDefault(
      java.lang.String key,
      com.github.peterrk.protocache.pb.ArrMap.Array defaultValue) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    java.util.Map<java.lang.String, com.github.peterrk.protocache.pb.ArrMap.Array> map =
        internalGet().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;string, .test.ArrMap.Array&gt; _ = 1;</code>
   */
  @java.lang.Override

  public com.github.peterrk.protocache.pb.ArrMap.Array getOrThrow(
      java.lang.String key) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    java.util.Map<java.lang.String, com.github.peterrk.protocache.pb.ArrMap.Array> map =
        internalGet().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    com.google.protobuf.GeneratedMessageV3
      .serializeStringMapTo(
        output,
        internalGet(),
        DefaultEntryHolder.defaultEntry,
        1);
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (java.util.Map.Entry<java.lang.String, com.github.peterrk.protocache.pb.ArrMap.Array> entry
         : internalGet().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, com.github.peterrk.protocache.pb.ArrMap.Array>
      __ = DefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, __);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.github.peterrk.protocache.pb.ArrMap)) {
      return super.equals(obj);
    }
    com.github.peterrk.protocache.pb.ArrMap other = (com.github.peterrk.protocache.pb.ArrMap) obj;

    if (!internalGet().equals(
        other.internalGet())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (!internalGet().getMap().isEmpty()) {
      hash = (37 * hash) + __FIELD_NUMBER;
      hash = (53 * hash) + internalGet().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.github.peterrk.protocache.pb.ArrMap parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.peterrk.protocache.pb.ArrMap parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.peterrk.protocache.pb.ArrMap parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.peterrk.protocache.pb.ArrMap parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.peterrk.protocache.pb.ArrMap parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.peterrk.protocache.pb.ArrMap parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.peterrk.protocache.pb.ArrMap parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.github.peterrk.protocache.pb.ArrMap parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.github.peterrk.protocache.pb.ArrMap parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.github.peterrk.protocache.pb.ArrMap parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.github.peterrk.protocache.pb.ArrMap parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.github.peterrk.protocache.pb.ArrMap parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.github.peterrk.protocache.pb.ArrMap prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code test.ArrMap}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:test.ArrMap)
      com.github.peterrk.protocache.pb.ArrMapOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.peterrk.protocache.pb.Test.internal_static_test_ArrMap_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 1:
          return internalGet();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMutableMapField(
        int number) {
      switch (number) {
        case 1:
          return internalGetMutable();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.peterrk.protocache.pb.Test.internal_static_test_ArrMap_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.peterrk.protocache.pb.ArrMap.class, com.github.peterrk.protocache.pb.ArrMap.Builder.class);
    }

    // Construct using com.github.peterrk.protocache.pb.ArrMap.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      internalGetMutable().clear();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.github.peterrk.protocache.pb.Test.internal_static_test_ArrMap_descriptor;
    }

    @java.lang.Override
    public com.github.peterrk.protocache.pb.ArrMap getDefaultInstanceForType() {
      return com.github.peterrk.protocache.pb.ArrMap.getDefaultInstance();
    }

    @java.lang.Override
    public com.github.peterrk.protocache.pb.ArrMap build() {
      com.github.peterrk.protocache.pb.ArrMap result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.github.peterrk.protocache.pb.ArrMap buildPartial() {
      com.github.peterrk.protocache.pb.ArrMap result = new com.github.peterrk.protocache.pb.ArrMap(this);
      int from_bitField0_ = bitField0_;
      result._ = internalGet();
      result._.makeImmutable();
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.github.peterrk.protocache.pb.ArrMap) {
        return mergeFrom((com.github.peterrk.protocache.pb.ArrMap)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.github.peterrk.protocache.pb.ArrMap other) {
      if (other == com.github.peterrk.protocache.pb.ArrMap.getDefaultInstance()) return this;
      internalGetMutable().mergeFrom(
          other.internalGet());
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.github.peterrk.protocache.pb.ArrMap parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.github.peterrk.protocache.pb.ArrMap) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.MapField<
        java.lang.String, com.github.peterrk.protocache.pb.ArrMap.Array> _;
    private com.google.protobuf.MapField<java.lang.String, com.github.peterrk.protocache.pb.ArrMap.Array>
    internalGet() {
      if (_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            DefaultEntryHolder.defaultEntry);
      }
      return _;
    }
    private com.google.protobuf.MapField<java.lang.String, com.github.peterrk.protocache.pb.ArrMap.Array>
    internalGetMutable() {
      onChanged();;
      if (_ == null) {
        _ = com.google.protobuf.MapField.newMapField(
            DefaultEntryHolder.defaultEntry);
      }
      if (!_.isMutable()) {
        _ = _.copy();
      }
      return _;
    }

    public int getCount() {
      return internalGet().getMap().size();
    }
    /**
     * <code>map&lt;string, .test.ArrMap.Array&gt; _ = 1;</code>
     */

    @java.lang.Override
    public boolean contains(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGet().getMap().containsKey(key);
    }
    /**
     * Use {@link #getMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, com.github.peterrk.protocache.pb.ArrMap.Array> get() {
      return getMap();
    }
    /**
     * <code>map&lt;string, .test.ArrMap.Array&gt; _ = 1;</code>
     */
    @java.lang.Override

    public java.util.Map<java.lang.String, com.github.peterrk.protocache.pb.ArrMap.Array> getMap() {
      return internalGet().getMap();
    }
    /**
     * <code>map&lt;string, .test.ArrMap.Array&gt; _ = 1;</code>
     */
    @java.lang.Override

    public com.github.peterrk.protocache.pb.ArrMap.Array getOrDefault(
        java.lang.String key,
        com.github.peterrk.protocache.pb.ArrMap.Array defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, com.github.peterrk.protocache.pb.ArrMap.Array> map =
          internalGet().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, .test.ArrMap.Array&gt; _ = 1;</code>
     */
    @java.lang.Override

    public com.github.peterrk.protocache.pb.ArrMap.Array getOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, com.github.peterrk.protocache.pb.ArrMap.Array> map =
          internalGet().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

//    public Builder clear() {
//      internalGetMutable().getMutableMap()
//          .clear();
//      return this;
//    }
    /**
     * <code>map&lt;string, .test.ArrMap.Array&gt; _ = 1;</code>
     */

    public Builder remove(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      internalGetMutable().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, com.github.peterrk.protocache.pb.ArrMap.Array>
    getMutable() {
      return internalGetMutable().getMutableMap();
    }
    /**
     * <code>map&lt;string, .test.ArrMap.Array&gt; _ = 1;</code>
     */
    public Builder put(
        java.lang.String key,
        com.github.peterrk.protocache.pb.ArrMap.Array value) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      if (value == null) { throw new java.lang.NullPointerException(); }
      internalGetMutable().getMutableMap()
          .put(key, value);
      return this;
    }
    /**
     * <code>map&lt;string, .test.ArrMap.Array&gt; _ = 1;</code>
     */

    public Builder putAll(
        java.util.Map<java.lang.String, com.github.peterrk.protocache.pb.ArrMap.Array> values) {
      internalGetMutable().getMutableMap()
          .putAll(values);
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:test.ArrMap)
  }

  // @@protoc_insertion_point(class_scope:test.ArrMap)
  private static final com.github.peterrk.protocache.pb.ArrMap DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.github.peterrk.protocache.pb.ArrMap();
  }

  public static com.github.peterrk.protocache.pb.ArrMap getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ArrMap>
      PARSER = new com.google.protobuf.AbstractParser<ArrMap>() {
    @java.lang.Override
    public ArrMap parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ArrMap(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ArrMap> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ArrMap> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.github.peterrk.protocache.pb.ArrMap getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

