// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test.proto

package com.github.peterrk.protocache.pb;

public interface ArrMapOrBuilder extends
    // @@protoc_insertion_point(interface_extends:test.ArrMap)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>map&lt;string, .test.ArrMap.Array&gt; _ = 1;</code>
   */
  int getCount();
  /**
   * <code>map&lt;string, .test.ArrMap.Array&gt; _ = 1;</code>
   */
  boolean contains(
      java.lang.String key);
  /**
   * Use {@link #getMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, com.github.peterrk.protocache.pb.ArrMap.Array>
  get();
  /**
   * <code>map&lt;string, .test.ArrMap.Array&gt; _ = 1;</code>
   */
  java.util.Map<java.lang.String, com.github.peterrk.protocache.pb.ArrMap.Array>
  getMap();
  /**
   * <code>map&lt;string, .test.ArrMap.Array&gt; _ = 1;</code>
   */

  com.github.peterrk.protocache.pb.ArrMap.Array getOrDefault(
      java.lang.String key,
      com.github.peterrk.protocache.pb.ArrMap.Array defaultValue);
  /**
   * <code>map&lt;string, .test.ArrMap.Array&gt; _ = 1;</code>
   */

  com.github.peterrk.protocache.pb.ArrMap.Array getOrThrow(
      java.lang.String key);
}
