// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: test.proto
// Protobuf Java Version: 4.30.2

package com.github.peterrk.protocache.pb;

public interface ArrMapOrBuilder extends
    // @@protoc_insertion_point(interface_extends:test.ArrMap)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>map&lt;string, .test.ArrMap.Array&gt; _x_ = 1;</code>
   */
  int getXCount();
  /**
   * <code>map&lt;string, .test.ArrMap.Array&gt; _x_ = 1;</code>
   */
  boolean containsX(
      java.lang.String key);
  /**
   * Use {@link #getXMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, com.github.peterrk.protocache.pb.ArrMap.Array>
  getX();
  /**
   * <code>map&lt;string, .test.ArrMap.Array&gt; _x_ = 1;</code>
   */
  java.util.Map<java.lang.String, com.github.peterrk.protocache.pb.ArrMap.Array>
  getXMap();
  /**
   * <code>map&lt;string, .test.ArrMap.Array&gt; _x_ = 1;</code>
   */
  /* nullable */
com.github.peterrk.protocache.pb.ArrMap.Array getXOrDefault(
      java.lang.String key,
      /* nullable */
com.github.peterrk.protocache.pb.ArrMap.Array defaultValue);
  /**
   * <code>map&lt;string, .test.ArrMap.Array&gt; _x_ = 1;</code>
   */
  com.github.peterrk.protocache.pb.ArrMap.Array getXOrThrow(
      java.lang.String key);
}
