// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: test.proto
// Protobuf Java Version: 4.30.2

package com.github.peterrk.protocache.pb;

public interface CyclicBOrBuilder extends
    // @@protoc_insertion_point(interface_extends:test.CyclicB)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 value = 1;</code>
   * @return The value.
   */
  int getValue();

  /**
   * <code>.test.CyclicA cyclic = 2;</code>
   * @return Whether the cyclic field is set.
   */
  boolean hasCyclic();
  /**
   * <code>.test.CyclicA cyclic = 2;</code>
   * @return The cyclic.
   */
  com.github.peterrk.protocache.pb.CyclicA getCyclic();
  /**
   * <code>.test.CyclicA cyclic = 2;</code>
   */
  com.github.peterrk.protocache.pb.CyclicAOrBuilder getCyclicOrBuilder();
}
