// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: test.proto
// Protobuf Java Version: 4.30.2

package com.github.peterrk.protocache.pb;

public interface DeprecatedOrBuilder extends
    // @@protoc_insertion_point(interface_extends:test.Deprecated)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 junk = 1 [deprecated = true];</code>
   * @deprecated test.Deprecated.junk is deprecated.
   *     See test.proto;l=82
   * @return The junk.
   */
  @java.lang.Deprecated int getJunk();
}
