// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: test.proto
// Protobuf Java Version: 4.30.2

package com.github.peterrk.protocache.pb;

/**
 * Protobuf type {@code test.Small}
 */
public final class Small extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:test.Small)
    SmallOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 30,
      /* patch= */ 2,
      /* suffix= */ "",
      Small.class.getName());
  }
  // Use Small.newBuilder() to construct.
  private Small(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private Small() {
    str_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.github.peterrk.protocache.pb.Test.internal_static_test_Small_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.github.peterrk.protocache.pb.Test.internal_static_test_Small_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.github.peterrk.protocache.pb.Small.class, com.github.peterrk.protocache.pb.Small.Builder.class);
  }

  public static final int I32_FIELD_NUMBER = 1;
  private int i32_ = 0;
  /**
   * <code>int32 i32 = 1;</code>
   * @return The i32.
   */
  @java.lang.Override
  public int getI32() {
    return i32_;
  }

  public static final int FLAG_FIELD_NUMBER = 2;
  private boolean flag_ = false;
  /**
   * <code>bool flag = 2;</code>
   * @return The flag.
   */
  @java.lang.Override
  public boolean getFlag() {
    return flag_;
  }

  public static final int STR_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object str_ = "";
  /**
   * <code>string str = 4;</code>
   * @return The str.
   */
  @java.lang.Override
  public java.lang.String getStr() {
    java.lang.Object ref = str_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      str_ = s;
      return s;
    }
  }
  /**
   * <code>string str = 4;</code>
   * @return The bytes for str.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getStrBytes() {
    java.lang.Object ref = str_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      str_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (i32_ != 0) {
      output.writeInt32(1, i32_);
    }
    if (flag_ != false) {
      output.writeBool(2, flag_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(str_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 4, str_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (i32_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, i32_);
    }
    if (flag_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(2, flag_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(str_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(4, str_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.github.peterrk.protocache.pb.Small)) {
      return super.equals(obj);
    }
    com.github.peterrk.protocache.pb.Small other = (com.github.peterrk.protocache.pb.Small) obj;

    if (getI32()
        != other.getI32()) return false;
    if (getFlag()
        != other.getFlag()) return false;
    if (!getStr()
        .equals(other.getStr())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + I32_FIELD_NUMBER;
    hash = (53 * hash) + getI32();
    hash = (37 * hash) + FLAG_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getFlag());
    hash = (37 * hash) + STR_FIELD_NUMBER;
    hash = (53 * hash) + getStr().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.github.peterrk.protocache.pb.Small parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.peterrk.protocache.pb.Small parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.peterrk.protocache.pb.Small parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.peterrk.protocache.pb.Small parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.peterrk.protocache.pb.Small parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.peterrk.protocache.pb.Small parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.peterrk.protocache.pb.Small parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.github.peterrk.protocache.pb.Small parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.github.peterrk.protocache.pb.Small parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.github.peterrk.protocache.pb.Small parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.github.peterrk.protocache.pb.Small parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.github.peterrk.protocache.pb.Small parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.github.peterrk.protocache.pb.Small prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code test.Small}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:test.Small)
      com.github.peterrk.protocache.pb.SmallOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.peterrk.protocache.pb.Test.internal_static_test_Small_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.peterrk.protocache.pb.Test.internal_static_test_Small_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.peterrk.protocache.pb.Small.class, com.github.peterrk.protocache.pb.Small.Builder.class);
    }

    // Construct using com.github.peterrk.protocache.pb.Small.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      i32_ = 0;
      flag_ = false;
      str_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.github.peterrk.protocache.pb.Test.internal_static_test_Small_descriptor;
    }

    @java.lang.Override
    public com.github.peterrk.protocache.pb.Small getDefaultInstanceForType() {
      return com.github.peterrk.protocache.pb.Small.getDefaultInstance();
    }

    @java.lang.Override
    public com.github.peterrk.protocache.pb.Small build() {
      com.github.peterrk.protocache.pb.Small result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.github.peterrk.protocache.pb.Small buildPartial() {
      com.github.peterrk.protocache.pb.Small result = new com.github.peterrk.protocache.pb.Small(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.github.peterrk.protocache.pb.Small result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.i32_ = i32_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.flag_ = flag_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.str_ = str_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.github.peterrk.protocache.pb.Small) {
        return mergeFrom((com.github.peterrk.protocache.pb.Small)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.github.peterrk.protocache.pb.Small other) {
      if (other == com.github.peterrk.protocache.pb.Small.getDefaultInstance()) return this;
      if (other.getI32() != 0) {
        setI32(other.getI32());
      }
      if (other.getFlag() != false) {
        setFlag(other.getFlag());
      }
      if (!other.getStr().isEmpty()) {
        str_ = other.str_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              i32_ = input.readInt32();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              flag_ = input.readBool();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 34: {
              str_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 34
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int i32_ ;
    /**
     * <code>int32 i32 = 1;</code>
     * @return The i32.
     */
    @java.lang.Override
    public int getI32() {
      return i32_;
    }
    /**
     * <code>int32 i32 = 1;</code>
     * @param value The i32 to set.
     * @return This builder for chaining.
     */
    public Builder setI32(int value) {

      i32_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>int32 i32 = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearI32() {
      bitField0_ = (bitField0_ & ~0x00000001);
      i32_ = 0;
      onChanged();
      return this;
    }

    private boolean flag_ ;
    /**
     * <code>bool flag = 2;</code>
     * @return The flag.
     */
    @java.lang.Override
    public boolean getFlag() {
      return flag_;
    }
    /**
     * <code>bool flag = 2;</code>
     * @param value The flag to set.
     * @return This builder for chaining.
     */
    public Builder setFlag(boolean value) {

      flag_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>bool flag = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearFlag() {
      bitField0_ = (bitField0_ & ~0x00000002);
      flag_ = false;
      onChanged();
      return this;
    }

    private java.lang.Object str_ = "";
    /**
     * <code>string str = 4;</code>
     * @return The str.
     */
    public java.lang.String getStr() {
      java.lang.Object ref = str_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        str_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string str = 4;</code>
     * @return The bytes for str.
     */
    public com.google.protobuf.ByteString
        getStrBytes() {
      java.lang.Object ref = str_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        str_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string str = 4;</code>
     * @param value The str to set.
     * @return This builder for chaining.
     */
    public Builder setStr(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      str_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string str = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearStr() {
      str_ = getDefaultInstance().getStr();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string str = 4;</code>
     * @param value The bytes for str to set.
     * @return This builder for chaining.
     */
    public Builder setStrBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      str_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:test.Small)
  }

  // @@protoc_insertion_point(class_scope:test.Small)
  private static final com.github.peterrk.protocache.pb.Small DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.github.peterrk.protocache.pb.Small();
  }

  public static com.github.peterrk.protocache.pb.Small getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Small>
      PARSER = new com.google.protobuf.AbstractParser<Small>() {
    @java.lang.Override
    public Small parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Small> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Small> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.github.peterrk.protocache.pb.Small getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

