// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: test.proto
// Protobuf Java Version: 4.30.2

package com.github.peterrk.protocache.pb;

public interface SmallOrBuilder extends
    // @@protoc_insertion_point(interface_extends:test.Small)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string str = 4;</code>
   * @return The str.
   */
  java.lang.String getStr();
  /**
   * <code>string str = 4;</code>
   * @return The bytes for str.
   */
  com.google.protobuf.ByteString
      getStrBytes();

  /**
   * <code>int32 i32 = 1;</code>
   * @return The i32.
   */
  int getI32();

  /**
   * <code>bool flag = 2;</code>
   * @return The flag.
   */
  boolean getFlag();

  /**
   * <pre>
   * skip 3
   * </pre>
   *
   * <code>int64 junk = 5 [deprecated = true];</code>
   * @deprecated test.Small.junk is deprecated.
   *     See test.proto;l=20
   * @return The junk.
   */
  @java.lang.Deprecated long getJunk();
}
