// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test.proto

package com.github.peterrk.protocache.pb;

/**
 * Protobuf type {@code test.Vec2D}
 */
public final class Vec2D extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:test.Vec2D)
    Vec2DOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Vec2D.newBuilder() to construct.
  private Vec2D(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Vec2D() {
    _ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Vec2D();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Vec2D(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              _ = new java.util.ArrayList<com.github.peterrk.protocache.pb.Vec2D.Vec1D>();
              mutable_bitField0_ |= 0x00000001;
            }
            _.add(
                input.readMessage(com.github.peterrk.protocache.pb.Vec2D.Vec1D.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        _ = java.util.Collections.unmodifiableList(_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.github.peterrk.protocache.pb.Test.internal_static_test_Vec2D_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.github.peterrk.protocache.pb.Test.internal_static_test_Vec2D_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.github.peterrk.protocache.pb.Vec2D.class, com.github.peterrk.protocache.pb.Vec2D.Builder.class);
  }

  public interface Vec1DOrBuilder extends
      // @@protoc_insertion_point(interface_extends:test.Vec2D.Vec1D)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated float _ = 1;</code>
     * @return A list containing the .
     */
    java.util.List<java.lang.Float> getList();
    /**
     * <code>repeated float _ = 1;</code>
     * @return The count of .
     */
    int getCount();
    /**
     * <code>repeated float _ = 1;</code>
     * @param index The index of the element to return.
     * @return The  at the given index.
     */
    float get(int index);
  }
  /**
   * Protobuf type {@code test.Vec2D.Vec1D}
   */
  public static final class Vec1D extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:test.Vec2D.Vec1D)
      Vec1DOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Vec1D.newBuilder() to construct.
    private Vec1D(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Vec1D() {
      _ = emptyFloatList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Vec1D();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Vec1D(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 13: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                _ = newFloatList();
                mutable_bitField0_ |= 0x00000001;
              }
              _.addFloat(input.readFloat());
              break;
            }
            case 10: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000001) != 0) && input.getBytesUntilLimit() > 0) {
                _ = newFloatList();
                mutable_bitField0_ |= 0x00000001;
              }
              while (input.getBytesUntilLimit() > 0) {
                _.addFloat(input.readFloat());
              }
              input.popLimit(limit);
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          _.makeImmutable(); // C
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.peterrk.protocache.pb.Test.internal_static_test_Vec2D_Vec1D_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.peterrk.protocache.pb.Test.internal_static_test_Vec2D_Vec1D_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.peterrk.protocache.pb.Vec2D.Vec1D.class, com.github.peterrk.protocache.pb.Vec2D.Vec1D.Builder.class);
    }

    public static final int __FIELD_NUMBER = 1;
    private com.google.protobuf.Internal.FloatList _;
    /**
     * <code>repeated float _ = 1;</code>
     * @return A list containing the .
     */
    @java.lang.Override
    public java.util.List<java.lang.Float>
        getList() {
      return _;
    }
    /**
     * <code>repeated float _ = 1;</code>
     * @return The count of .
     */
    public int getCount() {
      return _.size();
    }
    /**
     * <code>repeated float _ = 1;</code>
     * @param index The index of the element to return.
     * @return The  at the given index.
     */
    public float get(int index) {
      return _.getFloat(index);
    }
    private int MemoizedSerializedSize = -1;

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (getList().size() > 0) {
        output.writeUInt32NoTag(10);
        output.writeUInt32NoTag(MemoizedSerializedSize);
      }
      for (int i = 0; i < _.size(); i++) {
        output.writeFloatNoTag(_.getFloat(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        dataSize = 4 * getList().size();
        size += dataSize;
        if (!getList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        MemoizedSerializedSize = dataSize;
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.github.peterrk.protocache.pb.Vec2D.Vec1D)) {
        return super.equals(obj);
      }
      com.github.peterrk.protocache.pb.Vec2D.Vec1D other = (com.github.peterrk.protocache.pb.Vec2D.Vec1D) obj;

      if (!getList()
          .equals(other.getList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getCount() > 0) {
        hash = (37 * hash) + __FIELD_NUMBER;
        hash = (53 * hash) + getList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.github.peterrk.protocache.pb.Vec2D.Vec1D parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.peterrk.protocache.pb.Vec2D.Vec1D parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.peterrk.protocache.pb.Vec2D.Vec1D parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.peterrk.protocache.pb.Vec2D.Vec1D parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.peterrk.protocache.pb.Vec2D.Vec1D parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.peterrk.protocache.pb.Vec2D.Vec1D parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.peterrk.protocache.pb.Vec2D.Vec1D parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.github.peterrk.protocache.pb.Vec2D.Vec1D parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.github.peterrk.protocache.pb.Vec2D.Vec1D parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.github.peterrk.protocache.pb.Vec2D.Vec1D parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.github.peterrk.protocache.pb.Vec2D.Vec1D parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.github.peterrk.protocache.pb.Vec2D.Vec1D parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.github.peterrk.protocache.pb.Vec2D.Vec1D prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code test.Vec2D.Vec1D}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:test.Vec2D.Vec1D)
        com.github.peterrk.protocache.pb.Vec2D.Vec1DOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.github.peterrk.protocache.pb.Test.internal_static_test_Vec2D_Vec1D_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.github.peterrk.protocache.pb.Test.internal_static_test_Vec2D_Vec1D_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.github.peterrk.protocache.pb.Vec2D.Vec1D.class, com.github.peterrk.protocache.pb.Vec2D.Vec1D.Builder.class);
      }

      // Construct using com.github.peterrk.protocache.pb.Vec2D.Vec1D.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
//      @java.lang.Override
//      public Builder clear() {
//        super.clear();
//        _ = emptyFloatList();
//        bitField0_ = (bitField0_ & ~0x00000001);
//        return this;
//      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.github.peterrk.protocache.pb.Test.internal_static_test_Vec2D_Vec1D_descriptor;
      }

      @java.lang.Override
      public com.github.peterrk.protocache.pb.Vec2D.Vec1D getDefaultInstanceForType() {
        return com.github.peterrk.protocache.pb.Vec2D.Vec1D.getDefaultInstance();
      }

      @java.lang.Override
      public com.github.peterrk.protocache.pb.Vec2D.Vec1D build() {
        com.github.peterrk.protocache.pb.Vec2D.Vec1D result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.github.peterrk.protocache.pb.Vec2D.Vec1D buildPartial() {
        com.github.peterrk.protocache.pb.Vec2D.Vec1D result = new com.github.peterrk.protocache.pb.Vec2D.Vec1D(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) != 0)) {
          _.makeImmutable();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result._ = _;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.github.peterrk.protocache.pb.Vec2D.Vec1D) {
          return mergeFrom((com.github.peterrk.protocache.pb.Vec2D.Vec1D)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.github.peterrk.protocache.pb.Vec2D.Vec1D other) {
        if (other == com.github.peterrk.protocache.pb.Vec2D.Vec1D.getDefaultInstance()) return this;
        if (!other._.isEmpty()) {
          if (_.isEmpty()) {
            _ = other._;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureIsMutable();
            _.addAll(other._);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.github.peterrk.protocache.pb.Vec2D.Vec1D parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.github.peterrk.protocache.pb.Vec2D.Vec1D) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.Internal.FloatList _ = emptyFloatList();
      private void ensureIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          _ = mutableCopy(_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated float _ = 1;</code>
       * @return A list containing the .
       */
      public java.util.List<java.lang.Float>
          getList() {
        return ((bitField0_ & 0x00000001) != 0) ?
                 java.util.Collections.unmodifiableList(_) : _;
      }
      /**
       * <code>repeated float _ = 1;</code>
       * @return The count of .
       */
      public int getCount() {
        return _.size();
      }
      /**
       * <code>repeated float _ = 1;</code>
       * @param index The index of the element to return.
       * @return The  at the given index.
       */
      public float get(int index) {
        return _.getFloat(index);
      }
      /**
       * <code>repeated float _ = 1;</code>
       * @param index The index to set the value at.
       * @param value The  to set.
       * @return This builder for chaining.
       */
      public Builder set(
          int index, float value) {
        ensureIsMutable();
        _.setFloat(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated float _ = 1;</code>
       * @param value The  to add.
       * @return This builder for chaining.
       */
      public Builder add(float value) {
        ensureIsMutable();
        _.addFloat(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated float _ = 1;</code>
       * @param values The  to add.
       * @return This builder for chaining.
       */
      public Builder addAll(
          java.lang.Iterable<? extends java.lang.Float> values) {
        ensureIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, _);
        onChanged();
        return this;
      }
      /**
       * <code>repeated float _ = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clear() {
        _ = emptyFloatList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:test.Vec2D.Vec1D)
    }

    // @@protoc_insertion_point(class_scope:test.Vec2D.Vec1D)
    private static final com.github.peterrk.protocache.pb.Vec2D.Vec1D DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.github.peterrk.protocache.pb.Vec2D.Vec1D();
    }

    public static com.github.peterrk.protocache.pb.Vec2D.Vec1D getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Vec1D>
        PARSER = new com.google.protobuf.AbstractParser<Vec1D>() {
      @java.lang.Override
      public Vec1D parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Vec1D(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Vec1D> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Vec1D> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.github.peterrk.protocache.pb.Vec2D.Vec1D getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public static final int __FIELD_NUMBER = 1;
  private java.util.List<com.github.peterrk.protocache.pb.Vec2D.Vec1D> _;
  /**
   * <code>repeated .test.Vec2D.Vec1D _ = 1;</code>
   */
  @java.lang.Override
  public java.util.List<com.github.peterrk.protocache.pb.Vec2D.Vec1D> getList() {
    return _;
  }
  /**
   * <code>repeated .test.Vec2D.Vec1D _ = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.github.peterrk.protocache.pb.Vec2D.Vec1DOrBuilder> 
      getOrBuilderList() {
    return _;
  }
  /**
   * <code>repeated .test.Vec2D.Vec1D _ = 1;</code>
   */
  @java.lang.Override
  public int getCount() {
    return _.size();
  }
  /**
   * <code>repeated .test.Vec2D.Vec1D _ = 1;</code>
   */
  @java.lang.Override
  public com.github.peterrk.protocache.pb.Vec2D.Vec1D get(int index) {
    return _.get(index);
  }
  /**
   * <code>repeated .test.Vec2D.Vec1D _ = 1;</code>
   */
  @java.lang.Override
  public com.github.peterrk.protocache.pb.Vec2D.Vec1DOrBuilder getOrBuilder(
      int index) {
    return _.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < _.size(); i++) {
      output.writeMessage(1, _.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < _.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, _.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.github.peterrk.protocache.pb.Vec2D)) {
      return super.equals(obj);
    }
    com.github.peterrk.protocache.pb.Vec2D other = (com.github.peterrk.protocache.pb.Vec2D) obj;

    if (!getList()
        .equals(other.getList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getCount() > 0) {
      hash = (37 * hash) + __FIELD_NUMBER;
      hash = (53 * hash) + getList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.github.peterrk.protocache.pb.Vec2D parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.peterrk.protocache.pb.Vec2D parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.peterrk.protocache.pb.Vec2D parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.peterrk.protocache.pb.Vec2D parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.peterrk.protocache.pb.Vec2D parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.peterrk.protocache.pb.Vec2D parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.peterrk.protocache.pb.Vec2D parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.github.peterrk.protocache.pb.Vec2D parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.github.peterrk.protocache.pb.Vec2D parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.github.peterrk.protocache.pb.Vec2D parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.github.peterrk.protocache.pb.Vec2D parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.github.peterrk.protocache.pb.Vec2D parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.github.peterrk.protocache.pb.Vec2D prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code test.Vec2D}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:test.Vec2D)
      com.github.peterrk.protocache.pb.Vec2DOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.peterrk.protocache.pb.Test.internal_static_test_Vec2D_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.peterrk.protocache.pb.Test.internal_static_test_Vec2D_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.peterrk.protocache.pb.Vec2D.class, com.github.peterrk.protocache.pb.Vec2D.Builder.class);
    }

    // Construct using com.github.peterrk.protocache.pb.Vec2D.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (Builder_ == null) {
        _ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        Builder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.github.peterrk.protocache.pb.Test.internal_static_test_Vec2D_descriptor;
    }

    @java.lang.Override
    public com.github.peterrk.protocache.pb.Vec2D getDefaultInstanceForType() {
      return com.github.peterrk.protocache.pb.Vec2D.getDefaultInstance();
    }

    @java.lang.Override
    public com.github.peterrk.protocache.pb.Vec2D build() {
      com.github.peterrk.protocache.pb.Vec2D result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.github.peterrk.protocache.pb.Vec2D buildPartial() {
      com.github.peterrk.protocache.pb.Vec2D result = new com.github.peterrk.protocache.pb.Vec2D(this);
      int from_bitField0_ = bitField0_;
      if (Builder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          _ = java.util.Collections.unmodifiableList(_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result._ = _;
      } else {
        result._ = Builder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.github.peterrk.protocache.pb.Vec2D) {
        return mergeFrom((com.github.peterrk.protocache.pb.Vec2D)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.github.peterrk.protocache.pb.Vec2D other) {
      if (other == com.github.peterrk.protocache.pb.Vec2D.getDefaultInstance()) return this;
      if (Builder_ == null) {
        if (!other._.isEmpty()) {
          if (_.isEmpty()) {
            _ = other._;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureIsMutable();
            _.addAll(other._);
          }
          onChanged();
        }
      } else {
        if (!other._.isEmpty()) {
          if (Builder_.isEmpty()) {
            Builder_.dispose();
            Builder_ = null;
            _ = other._;
            bitField0_ = (bitField0_ & ~0x00000001);
            Builder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getFieldBuilder() : null;
          } else {
            Builder_.addAllMessages(other._);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.github.peterrk.protocache.pb.Vec2D parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.github.peterrk.protocache.pb.Vec2D) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<com.github.peterrk.protocache.pb.Vec2D.Vec1D> _ =
      java.util.Collections.emptyList();
    private void ensureIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        _ = new java.util.ArrayList<com.github.peterrk.protocache.pb.Vec2D.Vec1D>(_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.github.peterrk.protocache.pb.Vec2D.Vec1D, com.github.peterrk.protocache.pb.Vec2D.Vec1D.Builder, com.github.peterrk.protocache.pb.Vec2D.Vec1DOrBuilder> Builder_;

    /**
     * <code>repeated .test.Vec2D.Vec1D _ = 1;</code>
     */
    public java.util.List<com.github.peterrk.protocache.pb.Vec2D.Vec1D> getList() {
      if (Builder_ == null) {
        return java.util.Collections.unmodifiableList(_);
      } else {
        return Builder_.getMessageList();
      }
    }
    /**
     * <code>repeated .test.Vec2D.Vec1D _ = 1;</code>
     */
    public int getCount() {
      if (Builder_ == null) {
        return _.size();
      } else {
        return Builder_.getCount();
      }
    }
    /**
     * <code>repeated .test.Vec2D.Vec1D _ = 1;</code>
     */
    public com.github.peterrk.protocache.pb.Vec2D.Vec1D get(int index) {
      if (Builder_ == null) {
        return _.get(index);
      } else {
        return Builder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .test.Vec2D.Vec1D _ = 1;</code>
     */
    public Builder set(
        int index, com.github.peterrk.protocache.pb.Vec2D.Vec1D value) {
      if (Builder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureIsMutable();
        _.set(index, value);
        onChanged();
      } else {
        Builder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .test.Vec2D.Vec1D _ = 1;</code>
     */
    public Builder set(
        int index, com.github.peterrk.protocache.pb.Vec2D.Vec1D.Builder builderForValue) {
      if (Builder_ == null) {
        ensureIsMutable();
        _.set(index, builderForValue.build());
        onChanged();
      } else {
        Builder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .test.Vec2D.Vec1D _ = 1;</code>
     */
    public Builder add(com.github.peterrk.protocache.pb.Vec2D.Vec1D value) {
      if (Builder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureIsMutable();
        _.add(value);
        onChanged();
      } else {
        Builder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .test.Vec2D.Vec1D _ = 1;</code>
     */
    public Builder add(
        int index, com.github.peterrk.protocache.pb.Vec2D.Vec1D value) {
      if (Builder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureIsMutable();
        _.add(index, value);
        onChanged();
      } else {
        Builder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .test.Vec2D.Vec1D _ = 1;</code>
     */
    public Builder add(
        com.github.peterrk.protocache.pb.Vec2D.Vec1D.Builder builderForValue) {
      if (Builder_ == null) {
        ensureIsMutable();
        _.add(builderForValue.build());
        onChanged();
      } else {
        Builder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .test.Vec2D.Vec1D _ = 1;</code>
     */
    public Builder add(
        int index, com.github.peterrk.protocache.pb.Vec2D.Vec1D.Builder builderForValue) {
      if (Builder_ == null) {
        ensureIsMutable();
        _.add(index, builderForValue.build());
        onChanged();
      } else {
        Builder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .test.Vec2D.Vec1D _ = 1;</code>
     */
    public Builder addAll(
        java.lang.Iterable<? extends com.github.peterrk.protocache.pb.Vec2D.Vec1D> values) {
      if (Builder_ == null) {
        ensureIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, _);
        onChanged();
      } else {
        Builder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .test.Vec2D.Vec1D _ = 1;</code>
     */
//    public Builder clear() {
//      if (Builder_ == null) {
//        _ = java.util.Collections.emptyList();
//        bitField0_ = (bitField0_ & ~0x00000001);
//        onChanged();
//      } else {
//        Builder_.clear();
//      }
//      return this;
//    }
    /**
     * <code>repeated .test.Vec2D.Vec1D _ = 1;</code>
     */
    public Builder remove(int index) {
      if (Builder_ == null) {
        ensureIsMutable();
        _.remove(index);
        onChanged();
      } else {
        Builder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .test.Vec2D.Vec1D _ = 1;</code>
     */
    public com.github.peterrk.protocache.pb.Vec2D.Vec1D.Builder getBuilder(
        int index) {
      return getFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .test.Vec2D.Vec1D _ = 1;</code>
     */
    public com.github.peterrk.protocache.pb.Vec2D.Vec1DOrBuilder getOrBuilder(
        int index) {
      if (Builder_ == null) {
        return _.get(index);  } else {
        return Builder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .test.Vec2D.Vec1D _ = 1;</code>
     */
    public java.util.List<? extends com.github.peterrk.protocache.pb.Vec2D.Vec1DOrBuilder> 
         getOrBuilderList() {
      if (Builder_ != null) {
        return Builder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(_);
      }
    }
    /**
     * <code>repeated .test.Vec2D.Vec1D _ = 1;</code>
     */
    public com.github.peterrk.protocache.pb.Vec2D.Vec1D.Builder addBuilder() {
      return getFieldBuilder().addBuilder(
          com.github.peterrk.protocache.pb.Vec2D.Vec1D.getDefaultInstance());
    }
    /**
     * <code>repeated .test.Vec2D.Vec1D _ = 1;</code>
     */
    public com.github.peterrk.protocache.pb.Vec2D.Vec1D.Builder addBuilder(
        int index) {
      return getFieldBuilder().addBuilder(
          index, com.github.peterrk.protocache.pb.Vec2D.Vec1D.getDefaultInstance());
    }
    /**
     * <code>repeated .test.Vec2D.Vec1D _ = 1;</code>
     */
    public java.util.List<com.github.peterrk.protocache.pb.Vec2D.Vec1D.Builder> 
         getBuilderList() {
      return getFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.github.peterrk.protocache.pb.Vec2D.Vec1D, com.github.peterrk.protocache.pb.Vec2D.Vec1D.Builder, com.github.peterrk.protocache.pb.Vec2D.Vec1DOrBuilder> 
        getFieldBuilder() {
      if (Builder_ == null) {
        Builder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.github.peterrk.protocache.pb.Vec2D.Vec1D, com.github.peterrk.protocache.pb.Vec2D.Vec1D.Builder, com.github.peterrk.protocache.pb.Vec2D.Vec1DOrBuilder>(
                _,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        _ = null;
      }
      return Builder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:test.Vec2D)
  }

  // @@protoc_insertion_point(class_scope:test.Vec2D)
  private static final com.github.peterrk.protocache.pb.Vec2D DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.github.peterrk.protocache.pb.Vec2D();
  }

  public static com.github.peterrk.protocache.pb.Vec2D getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Vec2D>
      PARSER = new com.google.protobuf.AbstractParser<Vec2D>() {
    @java.lang.Override
    public Vec2D parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Vec2D(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Vec2D> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Vec2D> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.github.peterrk.protocache.pb.Vec2D getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

