// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test.proto

package com.github.peterrk.protocache.pb;

public interface Vec2DOrBuilder extends
    // @@protoc_insertion_point(interface_extends:test.Vec2D)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .test.Vec2D.Vec1D _ = 1;</code>
   */
  java.util.List<com.github.peterrk.protocache.pb.Vec2D.Vec1D> 
      getList();
  /**
   * <code>repeated .test.Vec2D.Vec1D _ = 1;</code>
   */
  com.github.peterrk.protocache.pb.Vec2D.Vec1D get(int index);
  /**
   * <code>repeated .test.Vec2D.Vec1D _ = 1;</code>
   */
  int getCount();
  /**
   * <code>repeated .test.Vec2D.Vec1D _ = 1;</code>
   */
  java.util.List<? extends com.github.peterrk.protocache.pb.Vec2D.Vec1DOrBuilder> 
      getOrBuilderList();
  /**
   * <code>repeated .test.Vec2D.Vec1D _ = 1;</code>
   */
  com.github.peterrk.protocache.pb.Vec2D.Vec1DOrBuilder getOrBuilder(
      int index);
}
