// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: test.proto
// Protobuf Java Version: 4.30.2

package com.github.peterrk.protocache.pb;

/**
 * Protobuf type {@code test.Vec2D}
 */
public final class Vec2D extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:test.Vec2D)
    Vec2DOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 30,
      /* patch= */ 2,
      /* suffix= */ "",
      Vec2D.class.getName());
  }
  // Use Vec2D.newBuilder() to construct.
  private Vec2D(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private Vec2D() {
    x_ = java.util.Collections.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.github.peterrk.protocache.pb.Test.internal_static_test_Vec2D_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.github.peterrk.protocache.pb.Test.internal_static_test_Vec2D_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.github.peterrk.protocache.pb.Vec2D.class, com.github.peterrk.protocache.pb.Vec2D.Builder.class);
  }

  public interface Vec1DOrBuilder extends
      // @@protoc_insertion_point(interface_extends:test.Vec2D.Vec1D)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated float x = 1;</code>
     * @return A list containing the x.
     */
    java.util.List<java.lang.Float> getXList();
    /**
     * <code>repeated float x = 1;</code>
     * @return The count of x.
     */
    int getXCount();
    /**
     * <code>repeated float x = 1;</code>
     * @param index The index of the element to return.
     * @return The x at the given index.
     */
    float getX(int index);
  }
  /**
   * Protobuf type {@code test.Vec2D.Vec1D}
   */
  public static final class Vec1D extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:test.Vec2D.Vec1D)
      Vec1DOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 30,
        /* patch= */ 2,
        /* suffix= */ "",
        Vec1D.class.getName());
    }
    // Use Vec1D.newBuilder() to construct.
    private Vec1D(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private Vec1D() {
      x_ = emptyFloatList();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.peterrk.protocache.pb.Test.internal_static_test_Vec2D_Vec1D_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.peterrk.protocache.pb.Test.internal_static_test_Vec2D_Vec1D_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.peterrk.protocache.pb.Vec2D.Vec1D.class, com.github.peterrk.protocache.pb.Vec2D.Vec1D.Builder.class);
    }

    public static final int X_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private com.google.protobuf.Internal.FloatList x_ =
        emptyFloatList();
    /**
     * <code>repeated float x = 1;</code>
     * @return A list containing the x.
     */
    @java.lang.Override
    public java.util.List<java.lang.Float>
        getXList() {
      return x_;
    }
    /**
     * <code>repeated float x = 1;</code>
     * @return The count of x.
     */
    public int getXCount() {
      return x_.size();
    }
    /**
     * <code>repeated float x = 1;</code>
     * @param index The index of the element to return.
     * @return The x at the given index.
     */
    public float getX(int index) {
      return x_.getFloat(index);
    }
    private int xMemoizedSerializedSize = -1;

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (getXList().size() > 0) {
        output.writeUInt32NoTag(10);
        output.writeUInt32NoTag(xMemoizedSerializedSize);
      }
      for (int i = 0; i < x_.size(); i++) {
        output.writeFloatNoTag(x_.getFloat(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        dataSize = 4 * getXList().size();
        size += dataSize;
        if (!getXList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        xMemoizedSerializedSize = dataSize;
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.github.peterrk.protocache.pb.Vec2D.Vec1D)) {
        return super.equals(obj);
      }
      com.github.peterrk.protocache.pb.Vec2D.Vec1D other = (com.github.peterrk.protocache.pb.Vec2D.Vec1D) obj;

      if (!getXList()
          .equals(other.getXList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getXCount() > 0) {
        hash = (37 * hash) + X_FIELD_NUMBER;
        hash = (53 * hash) + getXList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.github.peterrk.protocache.pb.Vec2D.Vec1D parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.peterrk.protocache.pb.Vec2D.Vec1D parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.peterrk.protocache.pb.Vec2D.Vec1D parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.peterrk.protocache.pb.Vec2D.Vec1D parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.peterrk.protocache.pb.Vec2D.Vec1D parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.peterrk.protocache.pb.Vec2D.Vec1D parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.peterrk.protocache.pb.Vec2D.Vec1D parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.github.peterrk.protocache.pb.Vec2D.Vec1D parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.github.peterrk.protocache.pb.Vec2D.Vec1D parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.github.peterrk.protocache.pb.Vec2D.Vec1D parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.github.peterrk.protocache.pb.Vec2D.Vec1D parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.github.peterrk.protocache.pb.Vec2D.Vec1D parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.github.peterrk.protocache.pb.Vec2D.Vec1D prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code test.Vec2D.Vec1D}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:test.Vec2D.Vec1D)
        com.github.peterrk.protocache.pb.Vec2D.Vec1DOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.github.peterrk.protocache.pb.Test.internal_static_test_Vec2D_Vec1D_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.github.peterrk.protocache.pb.Test.internal_static_test_Vec2D_Vec1D_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.github.peterrk.protocache.pb.Vec2D.Vec1D.class, com.github.peterrk.protocache.pb.Vec2D.Vec1D.Builder.class);
      }

      // Construct using com.github.peterrk.protocache.pb.Vec2D.Vec1D.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        x_ = emptyFloatList();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.github.peterrk.protocache.pb.Test.internal_static_test_Vec2D_Vec1D_descriptor;
      }

      @java.lang.Override
      public com.github.peterrk.protocache.pb.Vec2D.Vec1D getDefaultInstanceForType() {
        return com.github.peterrk.protocache.pb.Vec2D.Vec1D.getDefaultInstance();
      }

      @java.lang.Override
      public com.github.peterrk.protocache.pb.Vec2D.Vec1D build() {
        com.github.peterrk.protocache.pb.Vec2D.Vec1D result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.github.peterrk.protocache.pb.Vec2D.Vec1D buildPartial() {
        com.github.peterrk.protocache.pb.Vec2D.Vec1D result = new com.github.peterrk.protocache.pb.Vec2D.Vec1D(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.github.peterrk.protocache.pb.Vec2D.Vec1D result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          x_.makeImmutable();
          result.x_ = x_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.github.peterrk.protocache.pb.Vec2D.Vec1D) {
          return mergeFrom((com.github.peterrk.protocache.pb.Vec2D.Vec1D)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.github.peterrk.protocache.pb.Vec2D.Vec1D other) {
        if (other == com.github.peterrk.protocache.pb.Vec2D.Vec1D.getDefaultInstance()) return this;
        if (!other.x_.isEmpty()) {
          if (x_.isEmpty()) {
            x_ = other.x_;
            x_.makeImmutable();
            bitField0_ |= 0x00000001;
          } else {
            ensureXIsMutable();
            x_.addAll(other.x_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 13: {
                float v = input.readFloat();
                ensureXIsMutable();
                x_.addFloat(v);
                break;
              } // case 13
              case 10: {
                int length = input.readRawVarint32();
                int limit = input.pushLimit(length);
                int alloc = length > 4096 ? 4096 : length;
                ensureXIsMutable(alloc / 4);
                while (input.getBytesUntilLimit() > 0) {
                  x_.addFloat(input.readFloat());
                }
                input.popLimit(limit);
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.Internal.FloatList x_ = emptyFloatList();
      private void ensureXIsMutable() {
        if (!x_.isModifiable()) {
          x_ = makeMutableCopy(x_);
        }
        bitField0_ |= 0x00000001;
      }
      private void ensureXIsMutable(int capacity) {
        if (!x_.isModifiable()) {
          x_ = makeMutableCopy(x_, capacity);
        }
        bitField0_ |= 0x00000001;
      }
      /**
       * <code>repeated float x = 1;</code>
       * @return A list containing the x.
       */
      public java.util.List<java.lang.Float>
          getXList() {
        x_.makeImmutable();
        return x_;
      }
      /**
       * <code>repeated float x = 1;</code>
       * @return The count of x.
       */
      public int getXCount() {
        return x_.size();
      }
      /**
       * <code>repeated float x = 1;</code>
       * @param index The index of the element to return.
       * @return The x at the given index.
       */
      public float getX(int index) {
        return x_.getFloat(index);
      }
      /**
       * <code>repeated float x = 1;</code>
       * @param index The index to set the value at.
       * @param value The x to set.
       * @return This builder for chaining.
       */
      public Builder setX(
          int index, float value) {

        ensureXIsMutable();
        x_.setFloat(index, value);
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>repeated float x = 1;</code>
       * @param value The x to add.
       * @return This builder for chaining.
       */
      public Builder addX(float value) {

        ensureXIsMutable();
        x_.addFloat(value);
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>repeated float x = 1;</code>
       * @param values The x to add.
       * @return This builder for chaining.
       */
      public Builder addAllX(
          java.lang.Iterable<? extends java.lang.Float> values) {
        ensureXIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, x_);
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>repeated float x = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearX() {
        x_ = emptyFloatList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:test.Vec2D.Vec1D)
    }

    // @@protoc_insertion_point(class_scope:test.Vec2D.Vec1D)
    private static final com.github.peterrk.protocache.pb.Vec2D.Vec1D DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.github.peterrk.protocache.pb.Vec2D.Vec1D();
    }

    public static com.github.peterrk.protocache.pb.Vec2D.Vec1D getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Vec1D>
        PARSER = new com.google.protobuf.AbstractParser<Vec1D>() {
      @java.lang.Override
      public Vec1D parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Vec1D> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Vec1D> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.github.peterrk.protocache.pb.Vec2D.Vec1D getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public static final int X_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<com.github.peterrk.protocache.pb.Vec2D.Vec1D> x_;
  /**
   * <code>repeated .test.Vec2D.Vec1D x = 1;</code>
   */
  @java.lang.Override
  public java.util.List<com.github.peterrk.protocache.pb.Vec2D.Vec1D> getXList() {
    return x_;
  }
  /**
   * <code>repeated .test.Vec2D.Vec1D x = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.github.peterrk.protocache.pb.Vec2D.Vec1DOrBuilder> 
      getXOrBuilderList() {
    return x_;
  }
  /**
   * <code>repeated .test.Vec2D.Vec1D x = 1;</code>
   */
  @java.lang.Override
  public int getXCount() {
    return x_.size();
  }
  /**
   * <code>repeated .test.Vec2D.Vec1D x = 1;</code>
   */
  @java.lang.Override
  public com.github.peterrk.protocache.pb.Vec2D.Vec1D getX(int index) {
    return x_.get(index);
  }
  /**
   * <code>repeated .test.Vec2D.Vec1D x = 1;</code>
   */
  @java.lang.Override
  public com.github.peterrk.protocache.pb.Vec2D.Vec1DOrBuilder getXOrBuilder(
      int index) {
    return x_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < x_.size(); i++) {
      output.writeMessage(1, x_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < x_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, x_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.github.peterrk.protocache.pb.Vec2D)) {
      return super.equals(obj);
    }
    com.github.peterrk.protocache.pb.Vec2D other = (com.github.peterrk.protocache.pb.Vec2D) obj;

    if (!getXList()
        .equals(other.getXList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getXCount() > 0) {
      hash = (37 * hash) + X_FIELD_NUMBER;
      hash = (53 * hash) + getXList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.github.peterrk.protocache.pb.Vec2D parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.peterrk.protocache.pb.Vec2D parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.peterrk.protocache.pb.Vec2D parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.peterrk.protocache.pb.Vec2D parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.peterrk.protocache.pb.Vec2D parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.peterrk.protocache.pb.Vec2D parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.peterrk.protocache.pb.Vec2D parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.github.peterrk.protocache.pb.Vec2D parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.github.peterrk.protocache.pb.Vec2D parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.github.peterrk.protocache.pb.Vec2D parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.github.peterrk.protocache.pb.Vec2D parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.github.peterrk.protocache.pb.Vec2D parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.github.peterrk.protocache.pb.Vec2D prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code test.Vec2D}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:test.Vec2D)
      com.github.peterrk.protocache.pb.Vec2DOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.peterrk.protocache.pb.Test.internal_static_test_Vec2D_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.peterrk.protocache.pb.Test.internal_static_test_Vec2D_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.peterrk.protocache.pb.Vec2D.class, com.github.peterrk.protocache.pb.Vec2D.Builder.class);
    }

    // Construct using com.github.peterrk.protocache.pb.Vec2D.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (xBuilder_ == null) {
        x_ = java.util.Collections.emptyList();
      } else {
        x_ = null;
        xBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.github.peterrk.protocache.pb.Test.internal_static_test_Vec2D_descriptor;
    }

    @java.lang.Override
    public com.github.peterrk.protocache.pb.Vec2D getDefaultInstanceForType() {
      return com.github.peterrk.protocache.pb.Vec2D.getDefaultInstance();
    }

    @java.lang.Override
    public com.github.peterrk.protocache.pb.Vec2D build() {
      com.github.peterrk.protocache.pb.Vec2D result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.github.peterrk.protocache.pb.Vec2D buildPartial() {
      com.github.peterrk.protocache.pb.Vec2D result = new com.github.peterrk.protocache.pb.Vec2D(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.github.peterrk.protocache.pb.Vec2D result) {
      if (xBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          x_ = java.util.Collections.unmodifiableList(x_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.x_ = x_;
      } else {
        result.x_ = xBuilder_.build();
      }
    }

    private void buildPartial0(com.github.peterrk.protocache.pb.Vec2D result) {
      int from_bitField0_ = bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.github.peterrk.protocache.pb.Vec2D) {
        return mergeFrom((com.github.peterrk.protocache.pb.Vec2D)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.github.peterrk.protocache.pb.Vec2D other) {
      if (other == com.github.peterrk.protocache.pb.Vec2D.getDefaultInstance()) return this;
      if (xBuilder_ == null) {
        if (!other.x_.isEmpty()) {
          if (x_.isEmpty()) {
            x_ = other.x_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureXIsMutable();
            x_.addAll(other.x_);
          }
          onChanged();
        }
      } else {
        if (!other.x_.isEmpty()) {
          if (xBuilder_.isEmpty()) {
            xBuilder_.dispose();
            xBuilder_ = null;
            x_ = other.x_;
            bitField0_ = (bitField0_ & ~0x00000001);
            xBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 internalGetXFieldBuilder() : null;
          } else {
            xBuilder_.addAllMessages(other.x_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.github.peterrk.protocache.pb.Vec2D.Vec1D m =
                  input.readMessage(
                      com.github.peterrk.protocache.pb.Vec2D.Vec1D.parser(),
                      extensionRegistry);
              if (xBuilder_ == null) {
                ensureXIsMutable();
                x_.add(m);
              } else {
                xBuilder_.addMessage(m);
              }
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<com.github.peterrk.protocache.pb.Vec2D.Vec1D> x_ =
      java.util.Collections.emptyList();
    private void ensureXIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        x_ = new java.util.ArrayList<com.github.peterrk.protocache.pb.Vec2D.Vec1D>(x_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        com.github.peterrk.protocache.pb.Vec2D.Vec1D, com.github.peterrk.protocache.pb.Vec2D.Vec1D.Builder, com.github.peterrk.protocache.pb.Vec2D.Vec1DOrBuilder> xBuilder_;

    /**
     * <code>repeated .test.Vec2D.Vec1D x = 1;</code>
     */
    public java.util.List<com.github.peterrk.protocache.pb.Vec2D.Vec1D> getXList() {
      if (xBuilder_ == null) {
        return java.util.Collections.unmodifiableList(x_);
      } else {
        return xBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .test.Vec2D.Vec1D x = 1;</code>
     */
    public int getXCount() {
      if (xBuilder_ == null) {
        return x_.size();
      } else {
        return xBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .test.Vec2D.Vec1D x = 1;</code>
     */
    public com.github.peterrk.protocache.pb.Vec2D.Vec1D getX(int index) {
      if (xBuilder_ == null) {
        return x_.get(index);
      } else {
        return xBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .test.Vec2D.Vec1D x = 1;</code>
     */
    public Builder setX(
        int index, com.github.peterrk.protocache.pb.Vec2D.Vec1D value) {
      if (xBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureXIsMutable();
        x_.set(index, value);
        onChanged();
      } else {
        xBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .test.Vec2D.Vec1D x = 1;</code>
     */
    public Builder setX(
        int index, com.github.peterrk.protocache.pb.Vec2D.Vec1D.Builder builderForValue) {
      if (xBuilder_ == null) {
        ensureXIsMutable();
        x_.set(index, builderForValue.build());
        onChanged();
      } else {
        xBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .test.Vec2D.Vec1D x = 1;</code>
     */
    public Builder addX(com.github.peterrk.protocache.pb.Vec2D.Vec1D value) {
      if (xBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureXIsMutable();
        x_.add(value);
        onChanged();
      } else {
        xBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .test.Vec2D.Vec1D x = 1;</code>
     */
    public Builder addX(
        int index, com.github.peterrk.protocache.pb.Vec2D.Vec1D value) {
      if (xBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureXIsMutable();
        x_.add(index, value);
        onChanged();
      } else {
        xBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .test.Vec2D.Vec1D x = 1;</code>
     */
    public Builder addX(
        com.github.peterrk.protocache.pb.Vec2D.Vec1D.Builder builderForValue) {
      if (xBuilder_ == null) {
        ensureXIsMutable();
        x_.add(builderForValue.build());
        onChanged();
      } else {
        xBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .test.Vec2D.Vec1D x = 1;</code>
     */
    public Builder addX(
        int index, com.github.peterrk.protocache.pb.Vec2D.Vec1D.Builder builderForValue) {
      if (xBuilder_ == null) {
        ensureXIsMutable();
        x_.add(index, builderForValue.build());
        onChanged();
      } else {
        xBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .test.Vec2D.Vec1D x = 1;</code>
     */
    public Builder addAllX(
        java.lang.Iterable<? extends com.github.peterrk.protocache.pb.Vec2D.Vec1D> values) {
      if (xBuilder_ == null) {
        ensureXIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, x_);
        onChanged();
      } else {
        xBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .test.Vec2D.Vec1D x = 1;</code>
     */
    public Builder clearX() {
      if (xBuilder_ == null) {
        x_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        xBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .test.Vec2D.Vec1D x = 1;</code>
     */
    public Builder removeX(int index) {
      if (xBuilder_ == null) {
        ensureXIsMutable();
        x_.remove(index);
        onChanged();
      } else {
        xBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .test.Vec2D.Vec1D x = 1;</code>
     */
    public com.github.peterrk.protocache.pb.Vec2D.Vec1D.Builder getXBuilder(
        int index) {
      return internalGetXFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .test.Vec2D.Vec1D x = 1;</code>
     */
    public com.github.peterrk.protocache.pb.Vec2D.Vec1DOrBuilder getXOrBuilder(
        int index) {
      if (xBuilder_ == null) {
        return x_.get(index);  } else {
        return xBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .test.Vec2D.Vec1D x = 1;</code>
     */
    public java.util.List<? extends com.github.peterrk.protocache.pb.Vec2D.Vec1DOrBuilder> 
         getXOrBuilderList() {
      if (xBuilder_ != null) {
        return xBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(x_);
      }
    }
    /**
     * <code>repeated .test.Vec2D.Vec1D x = 1;</code>
     */
    public com.github.peterrk.protocache.pb.Vec2D.Vec1D.Builder addXBuilder() {
      return internalGetXFieldBuilder().addBuilder(
          com.github.peterrk.protocache.pb.Vec2D.Vec1D.getDefaultInstance());
    }
    /**
     * <code>repeated .test.Vec2D.Vec1D x = 1;</code>
     */
    public com.github.peterrk.protocache.pb.Vec2D.Vec1D.Builder addXBuilder(
        int index) {
      return internalGetXFieldBuilder().addBuilder(
          index, com.github.peterrk.protocache.pb.Vec2D.Vec1D.getDefaultInstance());
    }
    /**
     * <code>repeated .test.Vec2D.Vec1D x = 1;</code>
     */
    public java.util.List<com.github.peterrk.protocache.pb.Vec2D.Vec1D.Builder> 
         getXBuilderList() {
      return internalGetXFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        com.github.peterrk.protocache.pb.Vec2D.Vec1D, com.github.peterrk.protocache.pb.Vec2D.Vec1D.Builder, com.github.peterrk.protocache.pb.Vec2D.Vec1DOrBuilder> 
        internalGetXFieldBuilder() {
      if (xBuilder_ == null) {
        xBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            com.github.peterrk.protocache.pb.Vec2D.Vec1D, com.github.peterrk.protocache.pb.Vec2D.Vec1D.Builder, com.github.peterrk.protocache.pb.Vec2D.Vec1DOrBuilder>(
                x_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        x_ = null;
      }
      return xBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:test.Vec2D)
  }

  // @@protoc_insertion_point(class_scope:test.Vec2D)
  private static final com.github.peterrk.protocache.pb.Vec2D DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.github.peterrk.protocache.pb.Vec2D();
  }

  public static com.github.peterrk.protocache.pb.Vec2D getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Vec2D>
      PARSER = new com.google.protobuf.AbstractParser<Vec2D>() {
    @java.lang.Override
    public Vec2D parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Vec2D> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Vec2D> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.github.peterrk.protocache.pb.Vec2D getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

